SET FOREIGN_KEY_CHECKS = 0;
truncate table car_details;
truncate table car;
truncate table  return_report;
truncate table users_rents;
truncate table users;
truncate table rental_cars;
truncate table rental_employees;
truncate table rental;
truncate table rents;
truncate table role;
truncate table users_roles;
SET FOREIGN_KEY_CHECKS = 1;